# https://aka.ms/yaml

jobs:
- job: buildMacOS
  pool:
    vmImage: 'macOS-latest'
  steps:
    - script: |
        echo Cloning and Building bake
        git clone https://github.com/SanderMertens/bake
        make -C bake/build-$(uname)
        bake/bake setup
      displayName: Clone Bake
    - script: |
        echo Baking Flecs
        bake clone https://github.com/SanderMertens/flecs
        echo pwd
        echo $(Agent.HomeDirectory)
      displayName: Bake Flecs
    - task: CopyFiles@2
      continueOnError: false
      inputs:
        sourceFolder: '$(Agent.HomeDirectory)/bake/flecs/bin/x64-Darwin-debug'
        contents: '**/*.dylib'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'


- job: buildWindows
  pool:
    vmImage: 'windows-latest'
  steps:
    - script: echo win build
    - script: |
        echo Cloning bake
        git clone https://github.com/SanderMertens/bake
        make -C bake/build-Windows
        bake/bake setup
      displayName: Clone Bake
    - script: |
        echo Baking Flecs
        bake clone https://github.com/SanderMertens/flecs
      displayName: Bake Flecs
