# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: buildMacOS
  pool:
    vmImage: 'macOS-latest'
  steps:
    - script: |
        echo Cloning bake
        git clone https://github.com/SanderMertens/bake
        make -C bake/build-$(uname)
        bake/bake setup
      displayName: Clone Bake
    - script: |
        echo Baking Flecs
        bake clone https://github.com/SanderMertens/flecs
      displayName: Bake Flecs


- job: buildWindows
  pool:
    vmImage: 'windows-latest'
  steps:
    - script: echo win build
    - script: |
        echo Cloning bake
        git clone https://github.com/SanderMertens/bake
        make -C bake/build-Windows
        bake/bake setup
      displayName: Clone Bake
    - script: |
        echo Baking Flecs
        bake clone https://github.com/SanderMertens/flecs
      displayName: Bake Flecs

